### ISSUE TITLE
output sequences aren't always in the same orientation

### ISSUE THREAD

**Issue by sschmutz** [medvir/EnvSeq#1]
As far as I understand EnvSeq, giving `--reference` should result in an output where all sequences are in the same orientation. That's not always the case.

**Comment by mihuber** [comment]
Do you know of any example where this happened?

**Comment by sschmutz** [comment]
For example analysis output: `timavo:/analyses/plasmids/180802_plasmids/180802_plasmids.fasta`
from sequencing data: `timavo:/data/MiSeq/MiSeqOutput/180802_M02081_0314_000000000-C2KLB/`

Result from samples
- 3-4-2-tp1-cl33
- 3-4-2-tp1-cl18
- 3-4-2-tp1-cl38
- 3-4-2-tp1-cl8
seem to be in a different orientation than
- 3-4-2-tp1-cl2
- 3-4-2-tp1-cl5
- 3-4-2-tp1-cl46
- 3-4-2-tp1-cl57

I'm not sure if something has changed in the meantime (for example a different version of some tool is installed now). One could re-analyze those samples to check that.

**Comment by mihuber** [comment]
Multiple sequence alignment and correction of direction is only done if there are enough reads for multiple rounds of assembly, i.e. multiple contigs are available. Otherwise just the longest contig ist taken, which may be in the wrong direction.
```
if reference and r:  # if reference is given and replicates are present
        compute_msa(reference)
    else:  # if replicates were not found, take longest contig
```
